[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
# runner = "espflash flash --monitor"
runner = "espflash flash -B 921600 -f 80mhz -s 8mb --monitor" # Select this runner for espflash v2.x.x
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "master"

# For esp-idf-sys in MacOS
CRATE_CC_NO_DEFAULTS = "1"